//! Pure reconstruction of a table's CREATE TABLE DDL from raw pg_catalog parts.

use crate::commands::table::escape_identifier;
use serde::{Deserialize, Serialize};

/// One column's raw DDL ingredients, as read from pg_catalog.
#[derive(Debug, Clone)]
pub struct DdlColumn {
    pub name: String,
    pub type_str: String,
    pub not_null: bool,
    pub default_expr: Option<String>,
    /// pg_attribute.attidentity as text: "" (none), "a" (always), "d" (by default)
    pub identity: String,
    /// pg_attribute.attgenerated as text: "" (none), "s" (stored)
    pub generated: String,
}

/// One constraint, name + full definition from pg_get_constraintdef.
#[derive(Debug, Clone)]
pub struct DdlConstraint {
    pub name: String,
    pub definition: String,
}

/// All raw parts needed to compose a table's DDL.
#[derive(Debug, Clone, Default)]
pub struct TableDdlParts {
    pub columns: Vec<DdlColumn>,
    pub constraints: Vec<DdlConstraint>,
    /// Full `CREATE INDEX ...` statements (no trailing semicolon) from pg_get_indexdef,
    /// excluding indexes that back a constraint.
    pub index_defs: Vec<String>,
}

/// The three ready-to-display DDL variants sent to Swift.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TableDdl {
    pub columns_only: String,
    pub with_constraints: String,
    pub full: String,
}

/// Render a single column definition line (indented, no trailing comma).
fn render_column(col: &DdlColumn) -> String {
    let mut s = format!("    \"{}\" {}", escape_identifier(&col.name), col.type_str);
    if col.generated == "s" {
        if let Some(expr) = &col.default_expr {
            s.push_str(&format!(" GENERATED ALWAYS AS ({}) STORED", expr));
        }
        if col.not_null {
            s.push_str(" NOT NULL");
        }
    } else if col.identity == "a" {
        s.push_str(" GENERATED ALWAYS AS IDENTITY");
    } else if col.identity == "d" {
        s.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    } else {
        if let Some(expr) = &col.default_expr {
            s.push_str(&format!(" DEFAULT {}", expr));
        }
        if col.not_null {
            s.push_str(" NOT NULL");
        }
    }
    s
}

/// Render a constraint line (indented, no trailing comma).
fn render_constraint(con: &DdlConstraint) -> String {
    format!("    CONSTRAINT \"{}\" {}", escape_identifier(&con.name), con.definition)
}

/// Render a CREATE TABLE statement from column lines and optional constraint lines.
fn render_create_table(schema: &str, table: &str, col_lines: &[String], constraint_lines: &[String]) -> String {
    let mut body: Vec<String> = col_lines.to_vec();
    body.extend_from_slice(constraint_lines);
    format!("CREATE TABLE \"{}\".\"{}\" (\n{}\n);", escape_identifier(schema), escape_identifier(table), body.join(",\n"))
}

/// Compose the three DDL variants from raw parts. Pure — no I/O.
pub fn compose_table_ddl(schema: &str, table: &str, parts: &TableDdlParts) -> TableDdl {
    let col_lines: Vec<String> = parts.columns.iter().map(render_column).collect();
    let constraint_lines: Vec<String> = parts.constraints.iter().map(render_constraint).collect();

    let columns_only = render_create_table(schema, table, &col_lines, &[]);
    let with_constraints = render_create_table(schema, table, &col_lines, &constraint_lines);

    let mut full = with_constraints.clone();
    if !parts.index_defs.is_empty() {
        full.push_str("\n\n");
        full.push_str(
            &parts
                .index_defs
                .iter()
                .map(|d| format!("{};", d))
                .collect::<Vec<_>>()
                .join("\n"),
        );
    }

    TableDdl {
        columns_only,
        with_constraints,
        full,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_parts() -> TableDdlParts {
        TableDdlParts {
            columns: vec![
                DdlColumn {
                    name: "id".into(),
                    type_str: "bigint".into(),
                    not_null: true,
                    default_expr: None,
                    identity: "a".into(),
                    generated: "".into(),
                },
                DdlColumn {
                    name: "cust_id".into(),
                    type_str: "bigint".into(),
                    not_null: true,
                    default_expr: None,
                    identity: "".into(),
                    generated: "".into(),
                },
                DdlColumn {
                    name: "total".into(),
                    type_str: "numeric(10,2)".into(),
                    not_null: false,
                    default_expr: Some("0".into()),
                    identity: "".into(),
                    generated: "".into(),
                },
                DdlColumn {
                    name: "total_with_tax".into(),
                    type_str: "numeric(10,2)".into(),
                    not_null: false,
                    default_expr: Some("(total * 1.2)".into()),
                    identity: "".into(),
                    generated: "s".into(),
                },
                DdlColumn {
                    name: "created_at".into(),
                    type_str: "timestamp with time zone".into(),
                    not_null: true,
                    default_expr: Some("now()".into()),
                    identity: "".into(),
                    generated: "".into(),
                },
            ],
            constraints: vec![
                DdlConstraint {
                    name: "orders_pkey".into(),
                    definition: "PRIMARY KEY (id)".into(),
                },
                DdlConstraint {
                    name: "orders_total_check".into(),
                    definition: "CHECK ((total >= (0)::numeric))".into(),
                },
                DdlConstraint {
                    name: "orders_cust_fkey".into(),
                    definition: "FOREIGN KEY (cust_id) REFERENCES customers(id)".into(),
                },
            ],
            index_defs: vec![
                "CREATE INDEX orders_cust_idx ON public.orders USING btree (cust_id)".into(),
            ],
        }
    }

    #[test]
    fn columns_only_has_no_constraints_or_indexes() {
        let ddl = compose_table_ddl("public", "orders", &sample_parts());
        assert!(ddl.columns_only.starts_with("CREATE TABLE \"public\".\"orders\" ("));
        assert!(!ddl.columns_only.contains("CONSTRAINT"));
        assert!(!ddl.columns_only.contains("CREATE INDEX"));
        assert!(ddl.columns_only.contains("\"id\" bigint GENERATED ALWAYS AS IDENTITY"));
        assert!(ddl.columns_only.contains("\"total\" numeric(10,2) DEFAULT 0"));
    }

    #[test]
    fn not_null_column_with_default_renders_default_before_not_null() {
        let ddl = compose_table_ddl("public", "orders", &sample_parts());
        assert!(ddl
            .columns_only
            .contains("\"created_at\" timestamp with time zone DEFAULT now() NOT NULL"));
    }

    #[test]
    fn generated_column_renders_stored_expression() {
        let ddl = compose_table_ddl("public", "orders", &sample_parts());
        assert!(ddl
            .columns_only
            .contains("\"total_with_tax\" numeric(10,2) GENERATED ALWAYS AS ((total * 1.2)) STORED"));
    }

    #[test]
    fn with_constraints_has_constraints_but_no_indexes() {
        let ddl = compose_table_ddl("public", "orders", &sample_parts());
        assert!(ddl.with_constraints.contains("CONSTRAINT \"orders_pkey\" PRIMARY KEY (id)"));
        assert!(ddl
            .with_constraints
            .contains("CONSTRAINT \"orders_cust_fkey\" FOREIGN KEY (cust_id) REFERENCES customers(id)"));
        assert!(!ddl.with_constraints.contains("CREATE INDEX"));
    }

    #[test]
    fn full_appends_create_index_with_semicolon() {
        let ddl = compose_table_ddl("public", "orders", &sample_parts());
        assert!(ddl.full.contains("CONSTRAINT \"orders_pkey\""));
        assert!(ddl
            .full
            .contains("CREATE INDEX orders_cust_idx ON public.orders USING btree (cust_id);"));
    }

    #[test]
    fn no_indexes_means_full_equals_with_constraints() {
        let mut parts = sample_parts();
        parts.index_defs.clear();
        let ddl = compose_table_ddl("public", "orders", &parts);
        assert_eq!(ddl.full, ddl.with_constraints);
    }
}
