// The Phase 8 groundwork the four Apple Intelligence features build on:
// `GeneratedContentLabel`, `ModelFeedbackStore`, `ModelAvailability` and
// `IntelligenceGuard`.
//
// Two production dependencies are stood in for below, and BOTH are deliberate:
//
//  - `PharosCore` — `ModelFeedbackStore`'s default writer calls the FFI, and
//    there is no initialised core behind a `swiftc` binary. The stub records
//    that it was called; every test that exercises `record` replaces the
//    writer first, so the FFI path is never even the fallback.
//  - `AppStateManager` — `ModelAvailability` follows the stored setting
//    through its published `settings`. The real one reaches the core on
//    `init`. The stub publishes the one field this object reads.
//
// A stub can drift from the type it stands for. Each is therefore as small as
// the compiler allows, and no test asserts anything ABOUT the stubs — they
// exist to let the real types link.
import AppKit
import Combine

private var failures = 0

private func expect(_ condition: Bool, _ name: String) {
    if condition { print("PASS \(name)") } else { failures += 1; print("FAIL \(name)") }
}

private func expectEqual<T: Equatable>(_ actual: T, _ expected: T, _ name: String) {
    if actual == expected {
        print("PASS \(name)")
    } else {
        failures += 1
        print("FAIL \(name) — expected \(expected), got \(actual)")
    }
}

// MARK: - Stand-ins for the two production dependencies

struct AppSettings {
    var useAppleIntelligence: Bool = true
    /// `ModelAvailability` now follows the per-feature switches too. The real
    /// struct lives in `Pharos/Models/Settings.swift`; this is the same shape
    /// with the same defaults, so the object under test links. The rule those
    /// flags feed is covered on its own, against the REAL struct, in
    /// `scripts/test-model-availability-features.sh`.
    var intelligence = IntelligenceSettings()
}

struct IntelligenceSettings: Equatable {
    var describeQuery = true
    var explainErrors = true
    var suggestSavedQueryNames = true
    var nameTabsAutomatically = true
    var summarisePlans = true
    var suggestCharts = true
    var allowDraftingWriteStatements = true
}

@MainActor
final class AppStateManager: ObservableObject {
    static let shared = AppStateManager()
    @Published private(set) var settings = AppSettings()

    func setUseAppleIntelligence(_ on: Bool) {
        settings.useAppleIntelligence = on
    }
}

enum PharosCore {
    /// Set by nothing in the happy path: every test installs its own writer,
    /// so a rating reaching here is a bug in `ModelFeedbackStore`, not a
    /// deliberate call.
    nonisolated(unsafe) static var reachedTheFFI = false

    static func recordModelFeedback(feature: String, promptHash: String, rating: Int) throws {
        reachedTheFFI = true
    }
}

// MARK: - Entry point

// `runTests()` cannot be `@MainActor` — the shim calls it from nonisolated
// top-level scope. The body is, because AppKit is.
func runTests() {
    MainActor.assumeIsolated { runTestsOnMain() }
}

@MainActor
private func runTestsOnMain() {
    testLabelStructure()
    testLabelAccessibility()
    testThumbsUpRecordsAndTints()
    testThumbsDownAfterThumbsUpMovesTheTint()
    testRepeatedPressIsNotRecordedTwice()
    testRatingIsRecordedWithoutAPromptHash()
    testPromptHashShape()
    testAvailabilityForcedOff()
    testAvailabilityForcedOn()
    testSettingOffMakesItUnavailable()
    testGuardThrowsWhenUnavailable()
    testGuardPassesWhenAvailable()
    testInstructionsForbidTheDestructiveVerbs()

    print(failures == 0 ? "\nAll tests passed" : "\n\(failures) test(s) failed")
    exit(failures == 0 ? 0 : 1)
}

// MARK: - GeneratedContentLabel

@MainActor
private func testLabelStructure() {
    let label = GeneratedContentLabel(feature: "explain-error")
    label.layoutSubtreeIfNeeded()

    let captions = allTextFields(in: label).map(\.stringValue)
    expect(captions.contains("Generated by Apple Intelligence"),
           "label says the text was generated — got \(captions)")
    expectEqual(label.feedbackButtons.count, 2, "two thumb buttons")
    // The badge falls back to `sparkles` where the SDK has no
    // `apple.intelligence`; either way an image must be there, or the row
    // reads as plain grey text with no signal at all.
    expect(allImageViews(in: label).contains { $0.image != nil },
           "the row carries a badge image")
    expectEqual(label.fittingSize.height, 22, "the row is 22pt tall")
}

@MainActor
private func testLabelAccessibility() {
    let label = GeneratedContentLabel(feature: "explain-error")
    expectEqual(label.accessibilityRole(), NSAccessibility.Role.group, "the row is a group")
    expectEqual(label.accessibilityIdentifier(), "intelligence.label", "identifier")

    let axLabels = label.feedbackButtons.compactMap { $0.accessibilityLabel() }
    expectEqual(axLabels, ["Helpful", "Not helpful"], "thumb accessibility labels, in order")
}

@MainActor
private func testThumbsUpRecordsAndTints() {
    let label = hostedLabel(feature: "explain-error")
    label.promptHash = "0123456789abcdef"

    var delivered: [Int] = []
    label.onFeedback = { delivered.append($0) }
    let recorded = captureFeedback {
        label.feedbackButtons[0].performClick(nil)
    }

    expectEqual(delivered, [1], "onFeedback carries 1")
    expectEqual(recorded.count, 1, "one row written")
    if let first = recorded.first {
        expectEqual(first.feature, "explain-error", "the feature is recorded")
        expectEqual(first.promptHash, "0123456789abcdef", "the prompt hash is recorded")
        expectEqual(first.rating, 1, "the rating is recorded")
    }
    expectEqual(label.feedbackButtons[0].contentTintColor, NSColor.controlAccentColor,
                "thumbs up is tinted")
    expectEqual(label.feedbackButtons[1].contentTintColor, NSColor.secondaryLabelColor,
                "thumbs down stays secondary")
    expect(!PharosCore.reachedTheFFI, "the harness never reaches the FFI")
}

@MainActor
private func testThumbsDownAfterThumbsUpMovesTheTint() {
    let label = hostedLabel(feature: "draft-sql")
    label.promptHash = "fedcba9876543210"

    var delivered: [Int] = []
    label.onFeedback = { delivered.append($0) }
    let recorded = captureFeedback {
        label.feedbackButtons[0].performClick(nil)
        label.feedbackButtons[1].performClick(nil)
    }

    expectEqual(delivered, [1, -1], "a change of mind is delivered")
    expectEqual(recorded.map(\.rating), [1, -1], "both presses are recorded")
    // The tint has to MOVE, not merely be added: two lit thumbs would tell the
    // user their last press did nothing.
    expectEqual(label.feedbackButtons[0].contentTintColor, NSColor.secondaryLabelColor,
                "thumbs up goes back to secondary")
    expectEqual(label.feedbackButtons[1].contentTintColor, NSColor.controlAccentColor,
                "thumbs down is tinted")
}

@MainActor
private func testRepeatedPressIsNotRecordedTwice() {
    let label = hostedLabel(feature: "summarise-plan")
    label.promptHash = "aaaabbbbccccdddd"

    var delivered: [Int] = []
    label.onFeedback = { delivered.append($0) }
    let recorded = captureFeedback {
        label.feedbackButtons[0].performClick(nil)
        label.feedbackButtons[0].performClick(nil)
        label.feedbackButtons[0].performClick(nil)
    }

    expectEqual(recorded.count, 1, "leaning on the button writes one row")
    expectEqual(delivered, [1], "and reports once")
}

@MainActor
private func testRatingIsRecordedWithoutAPromptHash() {
    // A feature that forgets to set `promptHash` still gets its rating kept:
    // which feature was rated is the part worth having.
    let label = hostedLabel(feature: "suggest-name")
    let recorded = captureFeedback {
        label.feedbackButtons[1].performClick(nil)
    }
    expectEqual(recorded.count, 1, "the press is still recorded")
    expectEqual(recorded.first?.promptHash, "", "an absent hash is stored empty")
    expectEqual(recorded.first?.rating, -1, "the rating survives")
}

// MARK: - ModelFeedbackStore

@MainActor
private func testPromptHashShape() {
    let hash = ModelFeedbackStore.promptHash("SELECT * FROM flows WHERE id = 7")
    expectEqual(hash.count, 16, "16 characters")
    expect(hash.allSatisfy { $0.isHexDigit && !$0.isUppercase }, "lower-case hex only — got \(hash)")

    // Stable across calls, and different for different prompts. A constant
    // would satisfy the first claim alone.
    expectEqual(ModelFeedbackStore.promptHash("SELECT * FROM flows WHERE id = 7"), hash,
                "the same prompt gives the same hash")
    expect(ModelFeedbackStore.promptHash("SELECT * FROM flows WHERE id = 8") != hash,
           "a different prompt gives a different hash")
    // The digest is of the WHOLE prompt, not a prefix: two prompts that share
    // their first 200 characters must not collide.
    let shared = String(repeating: "x", count: 200)
    expect(ModelFeedbackStore.promptHash(shared + "a") != ModelFeedbackStore.promptHash(shared + "b"),
           "a late difference still changes the hash")
}

// MARK: - ModelAvailability

@MainActor
private func testAvailabilityForcedOff() {
    ModelAvailability.overrideForTesting = false
    defer { ModelAvailability.overrideForTesting = nil }

    expect(!ModelAvailability.shared.isAvailable, "forced off")
    expect(ModelAvailability.shared.unavailableReason?.isEmpty == false,
           "and a reason is given — got \(String(describing: ModelAvailability.shared.unavailableReason))")
}

@MainActor
private func testAvailabilityForcedOn() {
    ModelAvailability.overrideForTesting = true
    defer { ModelAvailability.overrideForTesting = nil }

    expect(ModelAvailability.shared.isAvailable, "forced on")
    expect(ModelAvailability.shared.unavailableReason == nil, "no reason when available")
}

/// The production path the override skips: clearing the checkbox must reach
/// `isAvailable` through the published settings, with nothing else pushing it.
///
/// The system side is whatever this Mac says, so the assertions are written to
/// hold either way: unavailable is unconditional, and the REASON is pinned only
/// where the model itself is usable — otherwise the system's own reason
/// correctly wins, and saying "turned off in Pharos settings" would send the
/// user to a checkbox that changes nothing.
@MainActor
private func testSettingOffMakesItUnavailable() {
    ModelAvailability.overrideForTesting = nil
    let availability = ModelAvailability.shared
    let modelRunsHere = availability.systemModelIsAvailable

    AppStateManager.shared.setUseAppleIntelligence(false)
    expect(!availability.isAvailable, "clearing the setting makes it unavailable")
    if modelRunsHere {
        expectEqual(availability.unavailableReason, ModelAvailability.settingOffReason,
                    "and names the setting as the reason")
    }

    AppStateManager.shared.setUseAppleIntelligence(true)
    expectEqual(availability.isAvailable, modelRunsHere,
                "setting it again restores whatever the model allows")
    if modelRunsHere {
        expect(availability.unavailableReason == nil, "and the reason is cleared")
    }
}

// MARK: - IntelligenceGuard

@MainActor
private func testGuardThrowsWhenUnavailable() {
    ModelAvailability.overrideForTesting = false
    defer { ModelAvailability.overrideForTesting = nil }

    do {
        try IntelligenceGuard.requireAvailable()
        expect(false, "requireAvailable throws when unavailable")
    } catch {
        expect(true, "requireAvailable throws when unavailable")
        // The thrown error must carry the reason, not a bare enum case: the
        // features put this straight in front of the user.
        let message = (error as? LocalizedError)?.errorDescription ?? ""
        expect(!message.isEmpty, "the error carries a user-readable reason — got \"\(message)\"")
        expectEqual(message, ModelAvailability.shared.unavailableReason ?? "",
                    "and it is the availability's own reason")
    }
}

@MainActor
private func testGuardPassesWhenAvailable() {
    ModelAvailability.overrideForTesting = true
    defer { ModelAvailability.overrideForTesting = nil }

    do {
        try IntelligenceGuard.requireAvailable()
        expect(true, "requireAvailable passes when available")
    } catch {
        expect(false, "requireAvailable passes when available — threw \(error)")
    }
}

// MARK: - IntelligenceInstructions

@MainActor
private func testInstructionsForbidTheDestructiveVerbs() {
    let text = IntelligenceInstructions.sqlSafety
    for verb in ["DROP", "DELETE", "TRUNCATE", "ALTER", "UPDATE"] {
        expect(text.contains(verb), "the shared instructions name \(verb)")
    }
    expect(text.contains("Do not run anything"), "and say the model does not run anything")
}

// MARK: - Helpers

/// Runs `body` with a writer that collects instead of writing, and returns
/// what it collected. The previous writer is restored, so one test cannot
/// leave another reading its rows.
@MainActor
private func captureFeedback(
    _ body: () -> Void
) -> [(feature: String, promptHash: String, rating: Int)] {
    var recorded: [(feature: String, promptHash: String, rating: Int)] = []
    let previous = ModelFeedbackStore.writer
    ModelFeedbackStore.writer = { feature, promptHash, rating in
        recorded.append((feature, promptHash, rating))
    }
    defer { ModelFeedbackStore.writer = previous }
    body()
    return recorded
}

/// A label inside a real (never ordered-front) window.
///
/// Load-bearing: `NSButton.performClick(_:)` does nothing for a button that is
/// not in a window, so a label built loose would report every rating as "no
/// press happened" and every assertion here would pass for the wrong reason.
/// The windows are kept alive for the run — a deallocated host takes its
/// buttons with it.
@MainActor
private var hostWindows: [NSWindow] = []

@MainActor
private func hostedLabel(feature: String) -> GeneratedContentLabel {
    let label = GeneratedContentLabel(feature: feature)
    let window = NSWindow(
        contentRect: NSRect(x: 0, y: 0, width: 400, height: 60),
        styleMask: [.titled], backing: .buffered, defer: false)
    let content = window.contentView!
    content.addSubview(label)
    NSLayoutConstraint.activate([
        label.leadingAnchor.constraint(equalTo: content.leadingAnchor),
        label.trailingAnchor.constraint(equalTo: content.trailingAnchor),
        label.topAnchor.constraint(equalTo: content.topAnchor),
    ])
    content.layoutSubtreeIfNeeded()
    hostWindows.append(window)
    return label
}

private func allTextFields(in view: NSView) -> [NSTextField] {
    var found: [NSTextField] = []
    if let field = view as? NSTextField { found.append(field) }
    for subview in view.subviews { found += allTextFields(in: subview) }
    return found
}

private func allImageViews(in view: NSView) -> [NSImageView] {
    var found: [NSImageView] = []
    if let image = view as? NSImageView { found.append(image) }
    for subview in view.subviews { found += allImageViews(in: subview) }
    return found
}
