/* Auto-generated by cbindgen. Do not edit. */

#ifndef PHAROS_CORE_H
#define PHAROS_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Callback invoked when an async operation completes.
 * - `context`: opaque pointer passed through from the caller (e.g. Swift continuation)
 * - `result_json`: JSON-encoded result on success, NULL on error
 * - `error_msg`: error message on failure, NULL on success
 *
 * Exactly one of `result_json` / `error_msg` will be non-NULL.
 * The caller must NOT free the strings --- they are freed by Rust after the callback returns.
 */
typedef void (*AsyncCallback)(void *context, const char *result_json, const char *error_msg);

/**
 * Load all connection configs. Returns JSON array. Caller must free.
 */
 char *pharos_load_connections(void);

/**
 * Save a connection config. `json` is a JSON-encoded ConnectionConfig.
 * Returns NULL on success, or an error message string (caller must free).
 */
 char *pharos_save_connection(const char *json);

/**
 * Delete a connection. Returns NULL on success or error string.
 */
 char *pharos_delete_connection(const char *connection_id);

/**
 * Connect to PostgreSQL. Calls `callback` when done.
 */
 void pharos_connect(const char *connection_id, AsyncCallback callback, void *context);

/**
 * Disconnect from PostgreSQL. Calls `callback` when done.
 */
 void pharos_disconnect(const char *connection_id, AsyncCallback callback, void *context);

/**
 * Test a connection config. `json` is JSON-encoded ConnectionConfig.
 */
 void pharos_test_connection(const char *json, AsyncCallback callback, void *context);

/**
 * Initialize the Rust runtime, SQLite database, and credential cache.
 * `app_data_dir` must be a valid UTF-8 path to the application support directory.
 * Returns true on success.
 */
 bool pharos_init(const char *app_data_dir);

/**
 * Shut down the Rust runtime. Call on app termination.
 */
 void pharos_shutdown(void);

/**
 * Free a string allocated by Rust. Must be called for every non-NULL string returned by pharos_* functions.
 */

void pharos_free_string(char *ptr);

/**
 * Format SQL with PostgreSQL conventions. Returns formatted SQL. Caller must free.
 */
 char *pharos_format_sql(const char *sql);

/**
 * Execute a SQL query. Returns JSON QueryResult via callback.
 */

void pharos_execute_query(const char *connection_id,
                          const char *sql,
                          const char *query_id,
                          int32_t limit,
                          const char *schema,
                          AsyncCallback callback,
                          void *context);

/**
 * Execute a statement (INSERT/UPDATE/DELETE). Returns JSON ExecuteResult via callback.
 */

void pharos_execute_statement(const char *connection_id,
                              const char *sql,
                              const char *schema,
                              AsyncCallback callback,
                              void *context);

/**
 * Fetch more rows. Returns JSON QueryResult via callback.
 */

void pharos_fetch_more_rows(const char *connection_id,
                            const char *sql,
                            int64_t limit,
                            int64_t offset,
                            const char *schema,
                            AsyncCallback callback,
                            void *context);

/**
 * Cancel a running query. Returns immediately (synchronous).
 */

void pharos_cancel_query(const char *connection_id,
                         const char *query_id,
                         AsyncCallback callback,
                         void *context);

/**
 * Validate SQL syntax. Returns JSON ValidationResult via callback.
 */

void pharos_validate_sql(const char *connection_id,
                         const char *sql,
                         const char *schema,
                         AsyncCallback callback,
                         void *context);

/**
 * Load query history. `json` is JSON with optional filters: {connectionId?, search?, limit?, offset?}.
 * Returns JSON array. Caller must free.
 */

char *pharos_load_query_history(const char *json);

/**
 * Delete a query history entry. Returns "true"/"false".
 */
 char *pharos_delete_query_history_entry(const char *entry_id);

/**
 * Get cached result data for a history entry. Returns JSON or NULL.
 */
 char *pharos_get_query_history_result(const char *entry_id);

/**
 * Load saved queries. Returns JSON array. Caller must free.
 */
 char *pharos_load_saved_queries(void);

/**
 * Create a saved query. `json` is JSON-encoded CreateSavedQuery. Returns JSON SavedQuery.
 */
 char *pharos_create_saved_query(const char *json);

/**
 * Update a saved query. `json` is JSON-encoded UpdateSavedQuery. Returns JSON SavedQuery or null.
 */
 char *pharos_update_saved_query(const char *json);

/**
 * Delete a saved query. Returns "true" or "false".
 */
 char *pharos_delete_saved_query(const char *query_id);

/**
 * Get schemas. Returns JSON array via callback.
 */
 void pharos_get_schemas(const char *connection_id, AsyncCallback callback, void *context);

/**
 * Get tables for a schema. Returns JSON array via callback.
 */

void pharos_get_tables(const char *connection_id,
                       const char *schema_name,
                       AsyncCallback callback,
                       void *context);

/**
 * Get columns for a table. Returns JSON array via callback.
 */

void pharos_get_columns(const char *connection_id,
                        const char *schema_name,
                        const char *table_name,
                        AsyncCallback callback,
                        void *context);

/**
 * Get all columns for all tables in a schema (batch). Returns JSON array via callback.
 */

void pharos_get_schema_columns(const char *connection_id,
                               const char *schema_name,
                               AsyncCallback callback,
                               void *context);

/**
 * Analyze a schema. Returns JSON AnalyzeResult via callback.
 */

void pharos_analyze_schema(const char *connection_id,
                           const char *schema_name,
                           AsyncCallback callback,
                           void *context);

/**
 * Get schema functions. Returns JSON array via callback.
 */

void pharos_get_schema_functions(const char *connection_id,
                                 const char *schema_name,
                                 AsyncCallback callback,
                                 void *context);

/**
 * Load settings. Returns JSON. Caller must free.
 */
 char *pharos_load_settings(void);

/**
 * Save settings. `json` is a JSON-encoded AppSettings.
 */
 char *pharos_save_settings(const char *json);

/**
 * Get table indexes. Returns JSON array via callback.
 */

void pharos_get_table_indexes(const char *connection_id,
                              const char *schema_name,
                              const char *table_name,
                              AsyncCallback callback,
                              void *context);

/**
 * Get table constraints. Returns JSON array via callback.
 */

void pharos_get_table_constraints(const char *connection_id,
                                  const char *schema_name,
                                  const char *table_name,
                                  AsyncCallback callback,
                                  void *context);

/**
 * Clone a table. `json` is JSON-encoded CloneTableOptions.
 */

void pharos_clone_table(const char *connection_id,
                        const char *json,
                        AsyncCallback callback,
                        void *context);

/**
 * Export table data. `json` is JSON-encoded ExportTableOptions.
 */

void pharos_export_table(const char *connection_id,
                         const char *json,
                         AsyncCallback callback,
                         void *context);

/**
 * Import CSV. `json` is JSON-encoded ImportCsvOptions.
 */

void pharos_import_csv(const char *connection_id,
                       const char *json,
                       AsyncCallback callback,
                       void *context);

#endif  /* PHAROS_CORE_H */
